version: '3.8'
services:
  postgres:
    image: postgres:15.5
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: akshayarora
      POSTGRES_PASSWORD: 191168
    ports:
      - "5432:5432"
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["sh", "-c", "java -jar /app/SocialMedia-0.0.1-SNAPSHOT.jar"]
