# Use an official PostgreSQL image as the base image
FROM postgres:15.5

# Copy custom configuration files if needed
# COPY postgresql.conf /etc/postgresql/postgresql.conf
# COPY pg_hba.conf /etc/postgresql/pg_hba.conf
